name: Build and push simple-reality
on:
  push:
    branches:
      - simple-reality
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: simple-reality
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Generate custom tag
        id: custom_tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          DATE_TAG=$(date +'%y%m%d')
          TAG=${DATE_TAG}-${SHORT_SHA}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Build Docker image for amd64
        run: |
          docker build . --file ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/simple-reality:${{ steps.custom_tag.outputs.tag }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/simple-reality:${{ steps.custom_tag.outputs.tag }} ${{ secrets.DOCKER_USERNAME }}/simple-reality:latest
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-reality:${{ steps.custom_tag.outputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-reality:latest
